# Домашнее задание по numpy
Все решения должны быть в 1-2 строки

In [1]:
import numpy as np # сделаю это за вас

In [2]:
# 0. зафиксируйте свой любимый seed 
np.random.seed(777)

# 1. Создайте трехмерный массив со случайными числами от 97 до 99
a = np.random.uniform(97, 99, 9)
print(a.reshape(3, 3, -1))

# 2. Создайте квдартраный массив размером 5x5 с целыми числами от -10 до 10 (зафиксируйте этот массив А)
A = np.random.randint(-10, 11, 25).reshape(5, 5)
print(A, "\n")

[[[97.30532747]
  [97.60471322]
  [97.12407283]]

 [[97.91972068]
  [98.67050677]
  [98.8539941 ]]

 [[98.45397797]
  [98.53699244]
  [97.53841013]]]
[[  4 -10  -9   8  10]
 [ -5  -3  -9  -3   0]
 [  8   8  -3   3  -6]
 [ -4  -8   0  -3   5]
 [-10  -2   9  -8   6]] 



In [3]:
# 3. Найдите собственные векторы предыдущего массива (А)
print(np.linalg.eig(A))

(array([-1.94029238+16.12340005j, -1.94029238-16.12340005j,
        3.91229601 +4.46546243j,  3.91229601 -4.46546243j,
       -2.94400726 +0.j        ]), array([[ 0.58632498+0.j        ,  0.58632498-0.j        ,
        -0.1065088 -0.50610861j, -0.1065088 +0.50610861j,
        -0.52961394+0.j        ],
       [ 0.18769671+0.20138561j,  0.18769671-0.20138561j,
         0.50091333+0.2355707j ,  0.50091333-0.2355707j ,
         0.34110059+0.j        ],
       [ 0.00168553-0.45947557j,  0.00168553+0.45947557j,
        -0.19143589-0.16616424j, -0.19143589+0.16616424j,
         0.03722025+0.j        ],
       [ 0.03377411+0.29852036j,  0.03377411-0.29852036j,
        -0.05168735+0.0536257j , -0.05168735-0.0536257j ,
         0.76466277+0.j        ],
       [-0.18609978+0.49439653j, -0.18609978-0.49439653j,
         0.59690592+0.j        ,  0.59690592-0.j        ,
         0.13063291+0.j        ]]))


In [4]:
# 4. Замените первые 5 чисел A на максимумы по столбцам и сохраните в массив B
B = np.copy(A)
B[0] = B.max(axis=0)


In [5]:
# 5. Конкатенируйте 4 массива в массив вида:

# A B
# C D
# где
#     C - транспонированный B
#     D - поэлементно умноженный A на С
# Размер массива должен быть 10x10

C = B.T
D = A * C

print(np.hstack([A,B,C,D]).reshape(10,10))

[[   4  -10   -9    8   10    8    8    9    8   10]
 [   8   -5    8   -4  -10   32   50  -72  -32 -100]
 [  -5   -3   -9   -3    0   -5   -3   -9   -3    0]
 [   8   -3    8   -8   -2  -40    9  -72   24    0]
 [   8    8   -3    3   -6    8    8   -3    3   -6]
 [   9   -9   -3    0    9   72  -72    9    0  -54]
 [  -4   -8    0   -3    5   -4   -8    0   -3    5]
 [   8   -3    3   -3   -8  -32   24    0    9  -40]
 [ -10   -2    9   -8    6  -10   -2    9   -8    6]
 [  10    0   -6    5    6 -100    0  -54  -40   36]]


# Если вы все сделали - то давайте двигаться дальше 😉